import {legacySeason} from './legacy-season.mjs';
const {PGlite} = await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth;
create function auth.jwt() returns jsonb language sql as $$ select current_setting('test.jwt',true)::jsonb $$;
create function auth.uid() returns uuid language sql as $$ select (auth.jwt()->>'sub')::uuid $$;`);
await db.exec(readFileSync(new URL('../schema.sql',import.meta.url),'utf8'));
const s=legacySeason();
await db.query('insert into public.league_config values(1,$1,0)',[s]);
await db.exec(`insert into public.league_players(email,name,is_admin) values('admin@example.com','Admin',true),('player@example.com','Player',false);`);
async function as(email){await db.query("select set_config('test.jwt',$1,false)",[JSON.stringify({email,sub:'11111111-1111-4111-8111-111111111111'})]);await db.exec('set role authenticated');}
await as('player@example.com');
// An ordinary player can predict original Traitors before any roles or rosters exist.
assert.ok(s.characters.every(c=>c.startingRole==='Unknown'));
assert.ok(s.episodes.every(ep=>Object.values(ep.roster).every(c=>c.role==='Unknown')));
await db.query("select public.save_entry('preseason',1,$1)",[{picks:['4','5','6']}]);
await assert.rejects(()=>db.query("select public.save_entry('preseason',1,$1)",[{picks:['4','5']}]),/locked or invalid/);
await assert.rejects(()=>db.query("select public.save_entry('preseason',1,$1)",[{picks:['4','4','6']}]),/Duplicate/);
await db.query("select public.save_entry('preseason',1,$1)",[{picks:['4','5','7']}]);
const preseasonRead=(await db.query('select public.read_league() as data')).rows[0].data;
assert.equal(preseasonRead.me.is_admin,false);
assert.equal(preseasonRead.entries.length,1,'Updating preseason replaces the earlier submission');
assert.deepEqual(preseasonRead.entries[0].payload.picks,['4','5','7']);
// Set up a weekly roster only after the preseason check.
await db.exec('reset role');
s.characters.forEach((c,i)=>s.episodes[1].roster[c.id]={role:i<2?'Traitor':'Faithful',status:'Active'});
await db.query('update public.league_config set state=$1 where id=1',[s]);
await as('player@example.com');
const draft={picks:['4','5','6','7','8','9','10','11'],captain:'4'};
await db.query("select public.save_entry('weekly',2,$1)",[draft]);
await assert.rejects(()=>db.query("select public.save_entry('weekly',2,$1)",[{...draft,captain:'12'}]),/Captain/);
await assert.rejects(()=>db.query('select public.save_league($1,0)',[s]),/Organiser/);
await assert.rejects(()=>db.query('select * from public.league_entries'),/permission denied/);
await db.exec('reset role');await as('admin@example.com');
let read=(await db.query('select public.read_league() as data')).rows[0].data;
assert.equal(read.entries.length,0,'Other players’ open drafts stay hidden even from organiser');
const invalid=structuredClone(s);invalid.episodes[1].roster['4'].status='Banished';
await assert.rejects(()=>db.query('select public.save_league($1,0)',[invalid]),/invalidate/);
s.episodes[1].locked=true;await db.query('select public.save_league($1,0)',[s]);
read=(await db.query('select public.read_league() as data')).rows[0].data;assert.equal(read.entries.length,1);
await assert.rejects(()=>db.query('select public.save_league($1,0)',[s]),/another window/);
await db.query("select public.add_player('new@example.com','New player')");
await db.exec('reset role');await as('player@example.com');
await assert.rejects(()=>db.query("select public.save_entry('weekly',2,$1)",[draft]),/locked/);
await assert.rejects(()=>db.query('select public.export_league()'),/Organiser/);
await db.exec('reset role');await as('outsider@example.com');
await assert.rejects(()=>db.query('select public.read_league()'),/not on this league/);
await assert.rejects(()=>db.query("select public.save_entry('preseason',1,$1)",[{picks:['4','5','6']}]),/Not a league member/);
// Fresh installs expose roles while ordinary players still cannot see email addresses.
await db.exec('reset role');await as('player@example.com');
read=(await db.query('select public.read_league() as data')).rows[0].data;
assert.ok(read.players.every(p=>typeof p.is_admin==='boolean'&&p.email===null));
const playerId=read.me.id;
const adminId=read.players.find(p=>p.name==='Admin').id;
await assert.rejects(()=>db.query('select public.set_player_organiser($1,true)',[playerId]),/Organiser/);

// Reproduce an installed league with the old RPCs, then apply the migration twice.
await db.exec('reset role');await as('admin@example.com');
const beforeUpgrade=(await db.query('select public.export_league() as data')).rows[0].data;
await db.exec('reset role');
const schema=readFileSync(new URL('../schema.sql',import.meta.url),'utf8');
const legacyRead=schema.slice(schema.indexOf('create function public.read_league()'),schema.indexOf('end $$;')+7)
 .replace('create function','create or replace function').replace(",'is_admin',is_admin",'');
await db.exec(legacyRead+'\ndrop function public.set_player_organiser(uuid,boolean);');
const migration=readFileSync(new URL('../migrations/20260907_organisers.sql',import.meta.url),'utf8');
await db.exec(migration);await db.exec(migration);
await as('admin@example.com');
assert.deepEqual((await db.query('select public.export_league() as data')).rows[0].data,beforeUpgrade,'Upgrade preserves all league data');
await assert.rejects(()=>db.query('select public.set_player_organiser($1,false)',[adminId]),/at least one organiser/);
await assert.rejects(()=>db.query('select public.set_player_organiser($1,null)',[playerId]),/Choose Player or Organiser/);
await assert.rejects(()=>db.query("select public.set_player_organiser('00000000-0000-4000-8000-000000000000',true)"),/Player not found/);
await db.query('select public.set_player_organiser($1,true)',[playerId]);
await db.exec('reset role');await as('player@example.com');
read=(await db.query('select public.read_league() as data')).rows[0].data;
assert.equal(read.me.is_admin,true,'Promoted player gets organiser access');
assert.equal(read.players.find(p=>p.id===playerId).is_admin,true);
assert.deepEqual(read.entries.find(e=>e.player_id===playerId&&e.kind==='weekly').payload,draft,'Promotion preserves submitted picks');
await db.query("select public.add_player('added-by-organiser@example.com','Additional player')");
await db.query('select public.export_league()');
await db.query('select public.save_league($1,1)',[s]);
await db.query('select public.set_player_organiser($1,false)',[adminId]);
await db.exec('reset role');await as('admin@example.com');
assert.equal((await db.query('select public.read_league() as data')).rows[0].data.me.is_admin,false);
await assert.rejects(()=>db.query('select public.set_player_organiser($1,true)',[adminId]),/Organiser/);
await assert.rejects(()=>db.query('select public.save_league($1,2)',[s]),/Organiser/);
await assert.rejects(()=>db.query("select public.add_player('denied@example.com','Denied')"),/Organiser/);
await assert.rejects(()=>db.query('select public.export_league()'),/Organiser/);
await db.exec('reset role');await as('player@example.com');
await assert.rejects(()=>db.query('select public.set_player_organiser($1,false)',[playerId]),/at least one organiser/);
await db.query('select public.set_player_organiser($1,true)',[adminId]);
await db.query('select public.set_player_organiser($1,false)',[playerId]);
read=(await db.query('select public.read_league() as data')).rows[0].data;
assert.equal(read.me.is_admin,false,'An organiser can step down when another remains');
assert.deepEqual(read.entries.find(e=>e.player_id===playerId&&e.kind==='weekly').payload,draft,'Demotion preserves submitted picks');
// The discovery fix must not bypass the organiser's preseason lock.
await db.exec('reset role');await as('admin@example.com');
const beforeLock=(await db.query('select public.read_league() as data')).rows[0].data;
beforeLock.state.preseasonLocked=true;
await db.query('select public.save_league($1,$2)',[beforeLock.state,beforeLock.revision]);
await db.exec('reset role');await as('player@example.com');
await assert.rejects(()=>db.query("select public.save_entry('preseason',1,$1)",[{picks:['4','5','6']}]),/locked or invalid/);
assert.deepEqual((await db.query('select public.read_league() as data')).rows[0].data.entries.find(e=>e.kind==='preseason').payload.picks,['4','5','7']);
await db.exec('reset role');await as('outsider@example.com');
await assert.rejects(()=>db.query('select public.set_player_organiser($1,true)',[playerId]),/Organiser/);
await db.exec('reset role; set role anon');
await assert.rejects(()=>db.query('select public.set_player_organiser($1,true)',[playerId]),/permission denied/);
console.log('Database passed: ordinary-player preseason submissions before role reveals, preseason lock enforcement, membership, draft privacy, scoring locks, revisions, organiser permissions, last-organiser protection and repeatable migration preserving league data.');
await db.close();
await import('./episode-one.database.mjs');
await import('./registration.database.mjs');
await import('./team-names.database.mjs');
await import('./ten-episodes.database.mjs');

await import('./scoring-rules.database.mjs');
await import('./broadcast-schedule.database.mjs');
