const programmeGroups = [
 {title:'Throughout the episode',ids:['TALKING_HEAD','POWER_MOVE','FAITHFUL_CORRECT_PRIVATE_READ']},
 {title:'Mission & shields',ids:['SHIELD_RECEIVED','MISSION_INDIVIDUAL_COMPLETE','MISSION_PAIR_COMPLETE','MISSION_GROUP_COMPLETE','MISSION_STANDOUT','MISSION_DISQUALIFIED','MISSION_QUIT','MISSION_THROWING','MISSION_GROUP_FAIL']},
 {title:'Murder & recruitment',ids:['BLOCKS_MURDER_WITH_SHIELD','TRAITOR_MURDER_SUCCESS','TRAITOR_IN_PERSON_MURDER','TRAITOR_MURDER_BLOCKED','CHARACTER_MURDERED','MURDERED_AFTER_CORRECT_READ','FAITHFUL_RECRUITED','TRAITOR_MURDER_BACKFIRES']},
 {title:'Round Table & banishment',ids:['VOTES_RECEIVED','FAITHFUL_VOTES_TRAITOR','VOTED_FOR_BANISHED_CHARACTER','FAITHFUL_VOTES_FAITHFUL','FAITHFUL_BANISHED_AS_FAITHFUL','FAITHFUL_PUBLICLY_NAMES_TRAITOR','FAITHFUL_LEADS_TRAITOR_BANISHMENT','FAITHFUL_HARD_DEFENDS_TRAITOR','TRAITOR_VOTES_FAITHFUL','TRAITOR_VOTES_BANISHED_FAITHFUL','TRAITOR_PUBLICLY_NAMES_FAITHFUL','TRAITOR_LEADS_FAITHFUL_BANISHMENT','TRAITOR_SWINGS_VOTE_TO_FAITHFUL','TRAITOR_FRAMES_FAITHFUL','TRAITOR_WEAPONISES_TRUE_INFO','TRAITOR_ZERO_VOTES','TRAITOR_SURVIVES_HEAT','TRAITOR_DEFENDED_BY_FAITHFUL','TRAITOR_VOTES_TRAITOR_NOT_BANISHED','TRAITOR_VOTES_BANISHED_TRAITOR','TRAITOR_BANISHED','TRAITOR_CAUGHT_IN_LIE','TRAITOR_OVERBUSES']},
 {title:'Episode outcomes',ids:['QUIT_SEASON','DISQUALIFIED','FAITHFUL_SURVIVES_EPISODE','TRAITOR_BUSES_AND_SURVIVES']}
];

const groupForRule = new Map(programmeGroups.flatMap(group=>group.ids.map(id=>[id,group.title])));

export function groupProgrammeEvents(rules) {
 const grouped = new Map([...programmeGroups.map(group=>[group.title,[]]),['Other events',[]]]);
 for (const rule of rules) grouped.get(groupForRule.get(rule.id)||'Other events').push(rule);
 return [...grouped].filter(([,events])=>events.length).map(([title,events])=>({title,rules:events}));
}